### PR TITLE
Dev ticket14 Remove created_at and updated_at info for a warehouse

### PR DESCRIPTION
**Pull request by Elizabeth-Sorescu**
Remove created_at and updated_at info for a warehouse

### CODE REVIEW

**Comment by hjy0102** [comment]
Is this ticket to populate GET all warehouses with real data?

**Review by ryn-ngn — APPROVED** [review]

**Comment by ryn-ngn** [comment]
Thanks Elizabeth

**Comment by Elizabeth-Sorescu** [comment]
> Is this ticket to populate GET all warehouses with real data?

Yes, Ginnie.

**Comment by Elizabeth-Sorescu** [comment]
> Thanks Elizabeth

Thank you, Ryan.

**Pull request merged**
