### PR TITLE
Dev db config

### PR DESCRIPTION
**Pull request by Elizabeth-Sorescu**
Set up a knex configuration file to connect to the proper database using the following:

client: mysql

connection: 

database: instock

Add the following variables to the .env:

DB_LOCAL_DBNAME

DB_LOCAL_USER

DB_LOCAL_PASSWORD

### CODE REVIEW

**Comment by Elizabeth-Sorescu** [comment]
This is for tickets 5 and 6

**Comment by zahrafalak** [comment]
Ticket #6 requirements:

Using the migrations and seeds folders provided in assets package (inside of DB Setup folder), add these folders to your project repository. 

Create the database schema before running the migrations. Check your knex configuration file for the proper name to use. 

Run the latest migration, then run the seeds file to introduce data into your database. After pushing the code, instruct your team members to do the same to ensure that everyone is using the same dataset. 

Note: Once this ticket is done, work with the other members of the team to use the migrations and seeds to set up their local databases.

**Review by zahrafalak — APPROVED** [review]

**Review by zahrafalak — APPROVED** [review]
Checked the code against ticket requirements. 
- The code includes migrations and seeds folders, as required.
- Seed data is provided and there's a seed file (init_seed.js) to populate the data into the database tables (warehouses and inventories). This aligns with the requirement.

**Review by Maedehshariifii — APPROVED** [review]

**Review by ryn-ngn — APPROVED** [review]

**Comment by Elizabeth-Sorescu** [comment]
Database is ready for API server

**Review by rjtbansal — COMMENTED** [review]
Well done setting these up

**Pull request merged**
